services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1453
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: e-commerce-website-database
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5433
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local